"""Initial migration2

Revision ID: 6088f29ff806
Revises: 
Create Date: 2024-07-10 11:50:48.457532

"""
from typing import Sequence, Union

from sqlalchemy import true

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6088f29ff806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean, default=True, nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
